#!/usr/bin/env bash

case "$1" in
    docker)
        echo "### building payara-react service docker ###"
        docker build -f Dockerfile --pull --no-cache . -t docker-io.dbc.dk/payara-react-service:devel || exit 1
        if [[ ! -z "$BUILD_NUMBER" ]]; then
            docker tag docker-io.dbc.dk/payara-react-service:devel docker-io.dbc.dk/payara-react-service:${BRANCH_NAME}-${BUILD_NUMBER}
        fi
        ;;

    *)
        echo "### building payara-react project ###"
        echo "### Look for build artifacts in target/ ###"

        mvn compile -Dmaven.test.skip=true || exit 1
        ;;
esac