#!/usr/bin/env bash

./stop || true
./build docker || exit 1

echo "### Starting payara-react service docker ###"

payara_react_service_port=${PAYARA_REACT_SERVICE_PORT:-8080}
docker run --rm --name payara-react-service -d -e JAVA_MAX_HEAP_SIZE=2G -e INSTANCE=devel -p ${payara_react_service_port}:8080 docker-io.dbc.dk/payara-react-service:devel

attempts=0
max_attempts=60
until $(curl --output /dev/null --silent --head --fail http://localhost:${payara_react_service_port}/status); do
    if [[ ${attempts} -eq ${max_attempts} ]]; then
        break
    fi

    printf '.'
    attempts=$(($attempts+1))
    sleep 0.5
done

echo ""
echo "### Status for payara-react service ###"
curl -vs http://localhost:${payara_react_service_port}/status
echo ""